-- Schema
DROP TABLE IF EXISTS students cascade;
DROP TABLE IF EXISTS addresses cascade;
DROP TABLE IF EXISTS classes cascade;
DROP TABLE IF EXISTS enrollments cascade;

CREATE TABLE students (
  id           integer generated by default as identity PRIMARY KEY,
  first_name   varchar(255) NOT NULL,
  last_name    varchar(255) NOT NULL,
  birthdate    date NOT NULL,
  address_id   integer
);

CREATE TABLE addresses (
  id            integer generated by default as identity PRIMARY KEY,
  line_1        varchar(255) NOT NULL,
  city          varchar(255) NOT NULL,
  state         varchar(255) NOT NULL,
  zipcode       integer NOT NULL
);

CREATE TABLE classes (
  id        integer generated by default as identity PRIMARY KEY,
  name      varchar(255) NOT NULL,
  credits   integer NOT NULL
);

CREATE TABLE enrollments (
  id          integer generated by default as identity PRIMARY KEY,
  student_id  integer references students(id),
  class_id    integer references classes(id),
  grade       varchar(10)
);

ALTER TABLE students
  ADD CONSTRAINT fk_address_id 
  FOREIGN KEY(address_id) 
  REFERENCES addresses(id);